# Generated by Django 3.2.3 on 2021-05-27 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hashirim_shelanu', '0003_auto_20210526_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prayer',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='service_type',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
