# Generated by Django 3.2.3 on 2021-07-15 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hashirim_shelanu', '0006_auto_20210605_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chordsheet',
            fields=[
                ('file', models.FileField(upload_to='chordsheets/')),
                ('contributor', models.CharField(max_length=100)),
                ('song', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='hashirim_shelanu.song')),
            ],
        ),
        migrations.RemoveField(
            model_name='song',
            name='chordsheet',
        ),
    ]
