# Generated by Django 3.2.3 on 2021-07-19 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hashirim_shelanu', '0009_auto_20210719_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='artist',
        ),
    ]
