# Generated by Django 3.2.3 on 2021-08-10 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hashirim_shelanu', '0012_alter_artist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prayer_position',
            name='prayer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hashirim_shelanu.prayer'),
        ),
        migrations.AlterField(
            model_name='prayer_position',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hashirim_shelanu.service_type'),
        ),
        migrations.AlterField(
            model_name='service_type',
            name='prayers',
            field=models.ManyToManyField(related_name='_hashirim_shelanu_service_type_prayers_+', through='hashirim_shelanu.Prayer_Position', to='hashirim_shelanu.Prayer'),
        ),
    ]
