# Generated by Django 4.0 on 2022-01-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hashirim_shelanu', '0014_auto_20210810_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='artists/'),
        ),
    ]
