# Generated by Django 4.0 on 2022-07-13 16:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('hashirim_shelanu', '0016_prayertag_songtag_alter_chordsheet_file_prayer_tags_and_more'), ('hashirim_shelanu', '0017_rename_prayertag_prayer_tag_rename_songtag_song_tag'), ('hashirim_shelanu', '0018_delete_prayer_tag_delete_song_tag_alter_prayer_tags_and_more'), ('hashirim_shelanu', '0019_taggedprayer_taggedsong_alter_prayer_tags_and_more'), ('hashirim_shelanu', '0020_remove_taggedsong_content_object_and_more'), ('hashirim_shelanu', '0021_prayertag_songtag_alter_prayer_tags_alter_song_tags')]

    dependencies = [
        ('hashirim_shelanu', '0015_artist_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chordsheet',
            name='file',
            field=models.FileField(upload_to='chordsheets/', validators=[django.core.validators.FileExtensionValidator(['pro'])]),
        ),
        migrations.CreateModel(
            name='PrayerTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SongTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='prayer',
            name='tags',
            field=models.ManyToManyField(related_name='prayers', to='hashirim_shelanu.PrayerTag'),
        ),
        migrations.AddField(
            model_name='song',
            name='tags',
            field=models.ManyToManyField(related_name='songs', to='hashirim_shelanu.SongTag'),
        ),
    ]
