# Generated by Django 4.0 on 2022-07-13 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hashirim_shelanu', '0016_prayertag_songtag_alter_chordsheet_file_prayer_tags_and_more_squashed_0021_prayertag_songtag_alter_prayer_tags_alter_song_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrayerTag',
            new_name='Prayer_Tag',
        ),
        migrations.RenameModel(
            old_name='SongTag',
            new_name='Song_Tag',
        ),
    ]
