# Generated by Django 4.0 on 2022-10-20 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hashirim_shelanu', '0017_rename_prayertag_prayer_tag_rename_songtag_song_tag_2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chordsheet_Contributor',
            new_name='ChordsheetContributor',
        ),
        migrations.RenameModel(
            old_name='Song_Tag',
            new_name='SongTag',
        ),
    ]
