# Generated by Django 4.0 on 2022-10-24 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hashirim_shelanu', '0018_rename_chordsheet_contributor_chordsheetcontributor_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prayer_Tag',
            new_name='PrayerTag',
        ),
    ]
