# Generated by Django 4.2.1 on 2023-06-06 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hashirim_shelanu', '0019_rename_prayer_tag_prayertag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hashirim_shelanu.artist'),
        ),
        migrations.AlterField(
            model_name='song',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='songs', to='hashirim_shelanu.songtag'),
        ),
    ]
