# Generated by Django 4.2.1 on 2023-06-06 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hashirim_shelanu', '0020_alter_song_artist_alter_song_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='apple_music',
            field=models.CharField(blank=True, help_text='Just the album and song IDs. for example: 1451484697?i=1451484701', max_length=30),
        ),
        migrations.AddField(
            model_name='song',
            name='spotify',
            field=models.CharField(blank=True, help_text='Just the ID, for example: 2aSi2nkU99ZaaOg2gB2hd5', max_length=50),
        ),
        migrations.AddField(
            model_name='song',
            name='youtube',
            field=models.CharField(blank=True, help_text='Just the ID, for example: VEJHr0BRh2c', max_length=20),
        ),
    ]
