# Generated by Django 3.2.3 on 2021-08-10 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hashirim_shelanu', '0013_auto_20210810_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prayer_Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField(unique=True)),
                ('prayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hashirim_shelanu.prayer')),
            ],
        ),
        migrations.CreateModel(
            name='Service_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('prayers', models.ManyToManyField(through='service_generator.Prayer_Position', to='hashirim_shelanu.Prayer')),
            ],
        ),
        migrations.AddField(
            model_name='prayer_position',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_generator.service_type'),
        ),
    ]
