# Generated by Django 3.2.3 on 2021-08-11 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('hashirim_shelanu', '0014_auto_20210810_1835'),
        ('service_generator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Element_Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Iyun_Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Other_Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Reading_Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Song_Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hashirim_shelanu.song')),
            ],
        ),
        migrations.CreateModel(
            name='Service_Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('element_type', models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'service_generator'), ('model', 'Song_Element')), models.Q(('app_label', 'service_generator'), ('model', 'Prayer_Element')), models.Q(('app_label', 'service_generator'), ('model', 'Reading_Element')), models.Q(('app_label', 'service_generator'), ('model', 'Iyun_Element')), models.Q(('app_label', 'service_generator'), ('model', 'Other_Element')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('element_list', models.ManyToManyField(through='service_generator.Element_Position', to='service_generator.Service_Element')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_generator.service_type')),
            ],
        ),
        migrations.CreateModel(
            name='Prayer_Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prayer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hashirim_shelanu.prayer')),
            ],
        ),
        migrations.AddField(
            model_name='element_position',
            name='element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_generator.service_element'),
        ),
        migrations.AddField(
            model_name='element_position',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_generator.service'),
        ),
    ]
