# Generated by Django 3.2.3 on 2021-05-27 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_generator', '0002_auto_20210526_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prayer',
            name='description',
            field=models.CharField(blank=True, max_length=4000),
        ),
        migrations.AlterField(
            model_name='service_type',
            name='description',
            field=models.CharField(blank=True, max_length=4000),
        ),
    ]
