# Generated by Django 3.2.3 on 2021-08-11 03:33

from django.db import migrations, models
import django.db.models.constraints


class Migration(migrations.Migration):

    dependencies = [
        ('hashirim_shelanu', '0014_auto_20210810_1835'),
        ('service_generator', '0002_auto_20210810_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prayer_element',
            name='prayer',
        ),
        migrations.RemoveField(
            model_name='song_element',
            name='song',
        ),
        migrations.AlterModelOptions(
            name='element_position',
            options={'ordering': ['index']},
        ),
        migrations.AlterModelOptions(
            name='prayer_position',
            options={'ordering': ['index']},
        ),
        migrations.AlterField(
            model_name='element_position',
            name='index',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AddConstraint(
            model_name='element_position',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('index',), name='element_unique_index'),
        ),
        migrations.AddConstraint(
            model_name='prayer_position',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('index',), name='prayer_unique_index'),
        ),
        migrations.DeleteModel(
            name='Prayer_Element',
        ),
        migrations.DeleteModel(
            name='Song_Element',
        ),
        migrations.CreateModel(
            name='Prayer_Element',
            fields=[
            ],
            options={
                'abstract': False,
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('hashirim_shelanu.prayer', models.Model),
        ),
        migrations.CreateModel(
            name='Song_Element',
            fields=[
            ],
            options={
                'abstract': False,
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('hashirim_shelanu.song', models.Model),
        ),
    ]
