# Generated by Django 4.0 on 2022-07-19 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_generator', '0005_iyun_element_description_iyun_element_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='element_list',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_type',
        ),
        migrations.DeleteModel(
            name='Element_Position',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
