# Generated by Django 4.0 on 2022-12-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_generator', '0009_rename_service_element_serviceelement'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceelement',
            name='_supporting',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
