# Generated by Django 4.1.2 on 2022-12-29 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hashirim_shelanu', '0019_rename_prayer_tag_prayertag'),
        ('service_generator', '0010_serviceelement__supporting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('display_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SectionPrayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField(unique=True)),
                ('prayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hashirim_shelanu.prayer')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_generator.section')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='ServiceTypeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField(unique=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_generator.section')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.DeleteModel(
            name='IyunElement',
        ),
        migrations.DeleteModel(
            name='OtherElement',
        ),
        migrations.RemoveField(
            model_name='prayerposition',
            name='prayer',
        ),
        migrations.RemoveField(
            model_name='prayerposition',
            name='service_type',
        ),
        migrations.DeleteModel(
            name='ReadingElement',
        ),
        migrations.RemoveField(
            model_name='serviceelement',
            name='element_type',
        ),
        migrations.DeleteModel(
            name='PrayerElement',
        ),
        migrations.DeleteModel(
            name='SongElement',
        ),
        migrations.RemoveField(
            model_name='servicetype',
            name='prayers',
        ),
        migrations.DeleteModel(
            name='PrayerPosition',
        ),
        migrations.DeleteModel(
            name='ServiceElement',
        ),
        migrations.AddField(
            model_name='servicetypesection',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_generator.servicetype'),
        ),
        migrations.AddField(
            model_name='section',
            name='prayers',
            field=models.ManyToManyField(through='service_generator.SectionPrayer', to='hashirim_shelanu.prayer'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='sections',
            field=models.ManyToManyField(through='service_generator.ServiceTypeSection', to='service_generator.section'),
        ),
    ]
