# Generated by Django 3.2.3 on 2021-07-19 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_generator', '0010_remove_song_artist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='temp_artist',
            new_name='artist',
        ),
    ]
